version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mysql-server
  
  mysql-server:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=user
      - MYSQL_PASSOWRD=123
      - MYSQL_ROOT_PASSWORD=123